generate_script:
  agent_config: "agent.yaml"
  agent:
    name: LLMAgent
    kwargs:
      code_file: step1_generate_script/agent.py
  next:
    - segment

segment:
  agent:
    name: CodeAgent
    kwargs:
      code_file: step2_segment/agent.py
  next:
    - generate_audio

generate_audio:
  agent:
    name: CodeAgent
    kwargs:
      code_file: step3_generate_audio/agent.py
  next:
    - generate_manim_code

generate_manim_code:
  agent:
    name: CodeAgent
    kwargs:
      code_file: step4_generate_manim_code/agent.py
  next:
    - fix_manim_code

fix_manim_code:
  agent:
    name: CodeAgent
    kwargs:
      code_file: step5_fix_manim_code/agent.py
  next:
    - render_manim

render_manim:
  agent:
    name: CodeAgent
    kwargs:
      code_file: step6_render_manim/agent.py
  next:
    - generate_illustration_prompts

generate_illustration_prompts:
  agent:
    name: CodeAgent
    kwargs:
      code_file: step7_generate_illustration_prompts/agent.py
  next:
    - generate_images

generate_images:
  agent:
    name: CodeAgent
    kwargs:
      code_file: step8_generate_images/agent.py
  next:
    - generate_subtitle

generate_subtitle:
  agent:
    name: CodeAgent
    kwargs:
      code_file: step9_generate_subtitle/agent.py
  next:
    - create_background

create_background:
  agent:
    name: CodeAgent
    kwargs:
      code_file: step10_create_background/agent.py
  next:
    - create_background

synthesize_video:
  description: Synthesize the video from the assets
  agent_config: "step3_synthesis_agent.yaml"
